#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/dist" --source_id="dist"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Monitoring tool" --log="/var/log/$app/$app.log"

#=================================================
# SPECIFIC SETUP
#=================================================
ynh_script_progression "Installing $app dependencies..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install --omit=dev
	ynh_hide_warnings ynh_exec_as_app npm run download-dist
popd

#=================================================
# CONFIGURING DATABASE
#=================================================

if [ $database != "none" ]; then
    ynh_script_progression "Configuring database..."

    if [ $database == "mariadb" ]; then
	    db_name=$(ynh_sanitize_dbid --db_name=$app)
		db_user=$db_name
		db_pwd=$(ynh_string_random --length=30)
		ynh_app_setting_set --key=db_name --value=$db_name
		ynh_app_setting_set --key=db_user --value=$db_user
		ynh_app_setting_set --key=db_pwd --value=$db_pwd

        ynh_mysql_create_db "$db_name" "$db_user" "$db_pwd"
		ynh_config_add --template="mysql.env" --destination="$install_dir/.env"
	elif [ $database == "sqlite" ]; then
		ynh_config_add --template="sqlite.env" --destination="$install_dir/.env"
	fi

	chmod 400 "$install_dir/.env"
	chown "$app:$app" "$install_dir/.env"
fi

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
