#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

#=================================================
# REMOVETHE MYSQL DATABASE
#=================================================
if [ $database == "mariadb" ]; then
	ynh_script_progression "Removing the database..."
	ynh_mysql_drop_db "$db_name" && ynh_mysql_drop_user "$db_user"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
